[mypy]
python_version = 3.10
plugins = mypy_django_plugin.main
ignore_missing_imports = True
exclude = venv/|migrations/|fixtures/

[mypy.plugins.django-stubs]
django_settings_module = config.settings